// packages/solid/src/ColorSchemeContext.ts
import type { Accessor } from 'solid-js';
import { createContext, useContext } from 'solid-js';

import type { ColorSchemeId, ColorSchemeListItem, ThemeMetaItem } from '@ohJohny/theme-builder-core';

export type { ColorSchemeListItem };

export type ColorSchemeContextValue = {
	readonly colorScheme: Accessor<ColorSchemeId>;
	readonly colorSchemeList: Accessor<readonly ColorSchemeListItem[]>;
	readonly labelShort: Accessor<string>;
	readonly changeColorScheme: (next?: ColorSchemeId) => void;
};

const ColorSchemeContext = createContext<ColorSchemeContextValue>();

export function useColorSchemeContext(): ColorSchemeContextValue {
	const context = useContext(ColorSchemeContext);
	if (!context) {
		throw new Error('useColorScheme must be used within a ThemeProvider');
	}
	return context;
}

export { ColorSchemeContext };

export type { ThemeMetaItem };

// packages/react/src/ColorSchemeContext.tsx
import {
	createContext,
	useContext,
	useMemo,
	useSyncExternalStore,
	type ReactNode,
} from 'react';

import {
	createColorSchemeStore,
	ThemeBuilder,
	type ColorSchemeId,
	type ColorSchemeStoreOptions,
	type Theme,
} from '@ohJohny/theme-builder-core';

import type { ColorSchemeStoreState } from '@ohJohny/theme-builder-core';

export type ColorSchemeContextValue = ReturnType<typeof createColorSchemeStore> & {
	readonly state: ColorSchemeStoreState;
};

const ColorSchemeContext = createContext<ColorSchemeContextValue | null>(null);

export function useColorSchemeContext(): ColorSchemeContextValue {
	const context = useContext(ColorSchemeContext);
	if (!context) {
		throw new Error('useColorScheme must be used within a ThemeProvider');
	}
	return context;
}

const ThemeContext = createContext<Theme | null>(null);

export function useTheme(): Theme {
	const theme = useContext(ThemeContext);
	if (!theme) {
		throw new ReferenceError('[useTheme] must be used within a ThemeProvider');
	}
	return theme;
}

export type ThemeProviderProps = ColorSchemeStoreOptions & {
	readonly children: ReactNode;
};

export function ThemeProvider(props: ThemeProviderProps) {
	const { children, ...storeOptions } = props;

	const store = useMemo(() => createColorSchemeStore(storeOptions), []);
	const state = useSyncExternalStore(store.subscribe, store.getState, store.getState);
	const theme = useMemo(() => ThemeBuilder.getInstance().getTheme(), []);

	const colorSchemeValue = useMemo(
		(): ColorSchemeContextValue => ({
			...store,
			state,
		}),
		[store, state],
	);

	return (
		<ColorSchemeContext.Provider value={colorSchemeValue}>
			<ThemeContext.Provider value={theme}>{children}</ThemeContext.Provider>
		</ColorSchemeContext.Provider>
	);
}

export type { ColorSchemeId, ThemeMetaItem, ThemeStorageConfig } from '@ohJohny/theme-builder-core';
