// packages/solid/src/components/ThemeProvider.tsx
/** @jsxImportSource solid-js */
import {
	createMemo,
	createSignal,
	mergeProps,
	onCleanup,
	onMount,
	splitProps,
	type ParentComponent,
} from 'solid-js';

import {
	createColorSchemeStore,
	ThemeBuilder,
	type ColorSchemeId,
	type ColorSchemeListItem,
	type ColorSchemeStoreOptions,
} from '@ohJohny/theme-builder-core';

import { ColorSchemeContext } from './ColorSchemeContext';
import { DeviceSizeProvider } from './DeviceSizeProvider';
import { getDefaultTheme, ThemeContext } from './useTheme';
import type { DeviceBreakpointsRem } from '../utils/types';

export type ThemeProviderProps = ColorSchemeStoreOptions & {
	readonly breakpointsRem?: Partial<DeviceBreakpointsRem>;
};

export const ThemeProvider: ParentComponent<ThemeProviderProps> = (props) => {
	const merged = mergeProps(
		{
			presetColorScheme: 'light' as const,
			applyColorSchemeOnMount: true,
		},
		props,
	);

	const [local, storeOptions] = splitProps(merged, ['children', 'breakpointsRem']);
	const store = createColorSchemeStore(storeOptions);
	const [snapshot, setSnapshot] = createSignal(store.getState());

	onMount(() => {
		const unsub = store.subscribe(() => setSnapshot(store.getState()));
		onCleanup(() => {
			unsub();
			store.dispose();
		});
	});

	const colorScheme = () => snapshot().colorScheme;
	const colorSchemeList = createMemo<readonly ColorSchemeListItem[]>(() => snapshot().colorSchemeList);
	const labelShort = createMemo(() => snapshot().labelShort);

	const colorSchemeValue = {
		colorScheme,
		colorSchemeList,
		labelShort,
		changeColorScheme: store.changeColorScheme,
	};

	const [themeVersion, setThemeVersion] = createSignal(0);
	onMount(() => {
		const unsubTheme = ThemeBuilder.getInstance().subscribe(() =>
			setThemeVersion((v) => v + 1),
		);
		onCleanup(() => unsubTheme());
	});
	const resolvedTheme = createMemo(() => {
		themeVersion();
		return getDefaultTheme();
	});

	return (
		<ColorSchemeContext.Provider value={colorSchemeValue}>
			<ThemeContext.Provider value={resolvedTheme}>
				<DeviceSizeProvider breakpointsRem={local.breakpointsRem}>
					{local.children}
				</DeviceSizeProvider>
			</ThemeContext.Provider>
		</ColorSchemeContext.Provider>
	);
};

// packages/react/src/ThemeProvider.tsx
import {
	useEffect,
	useMemo,
	useSyncExternalStore,
	type ReactNode,
} from 'react';

import {
	createColorSchemeStore,
	ThemeBuilder,
	type ColorSchemeStoreOptions,
} from '@ohJohny/theme-builder-core';

import {
	ColorSchemeContext,
	type ColorSchemeContextValue,
	ThemeContext,
} from './ColorSchemeContext';
import { DeviceSizeProvider } from './deviceSize/DeviceSizeProvider';
import type { DeviceBreakpointsRem } from './deviceSize/types';

export type ThemeProviderProps = ColorSchemeStoreOptions & {
	readonly breakpointsRem?: Partial<DeviceBreakpointsRem>;
	readonly children: ReactNode;
};

export function ThemeProvider(props: ThemeProviderProps) {
	const { children, breakpointsRem, ...storeOptions } = props;

	const store = useMemo(() => createColorSchemeStore(storeOptions), []);
	const state = useSyncExternalStore(store.subscribe, store.getState, store.getState);

	useEffect(() => {
		return () => store.dispose();
	}, [store]);

	const themeBuilder = ThemeBuilder.getInstance();
	const theme = useSyncExternalStore(
		(listener) => themeBuilder.subscribe(listener),
		() => themeBuilder.getTheme(),
		() => themeBuilder.getTheme(),
	);

	const colorSchemeValue = useMemo(
		(): ColorSchemeContextValue => ({
			...store,
			state,
		}),
		[store, state],
	);

	return (
		<ColorSchemeContext.Provider value={colorSchemeValue}>
			<ThemeContext.Provider value={theme}>
				<DeviceSizeProvider breakpointsRem={breakpointsRem}>{children}</DeviceSizeProvider>
			</ThemeContext.Provider>
		</ColorSchemeContext.Provider>
	);
}
