// packages/solid/src/components/SingletonThemeProvider.tsx
/** @jsxImportSource solid-js */
import {
	createMemo,
	createSignal,
	onCleanup,
	onMount,
	splitProps,
	type JSX,
} from 'solid-js';

import {
	peekOrCreateSharedColorSchemeStore,
	releaseSharedColorSchemeStore,
	retainSharedColorSchemeStore,
	type ColorSchemeStoreOptions,
	type CreatedTheme,
	type ReducedMotionPreference,
	type ThemeConfigInput,
} from '@ohJohny/theme-builder-core';

import { ColorSchemeContext } from './ColorSchemeContext';
import { DeviceSizeProvider } from './DeviceSizeProvider';
import { ReducedMotionProvider } from './ReducedMotionProvider';
import { ThemeContext } from './useTheme';
import type { DeviceBreakpoints } from '../utils/types';

export type SingletonThemeProviderProps<C extends ThemeConfigInput> = Omit<
	ColorSchemeStoreOptions,
	'schemes'
> & {
	readonly theme: CreatedTheme<C>;
	readonly breakpoints?: Partial<DeviceBreakpoints>;
	/** @deprecated Use {@link SingletonThemeProviderProps.breakpoints} */
	readonly breakpointsRem?: Partial<DeviceBreakpoints>;
	/**
	 * `true` / `false` force reduced motion on or off; `'auto'` (default) follows
	 * OS `prefers-reduced-motion`. `false` is not recommended — prefer `'auto'`.
	 */
	readonly reducedMotion?: ReducedMotionPreference;
};

export function SingletonThemeProvider<C extends ThemeConfigInput>(
	props: SingletonThemeProviderProps<C> & { children?: JSX.Element },
) {
	const [local, storeOptions] = splitProps(props, [
		'children',
		'breakpoints',
		'breakpointsRem',
		'reducedMotion',
		'theme',
	]);

	const store = peekOrCreateSharedColorSchemeStore({
		...storeOptions,
		schemes: local.theme.schemes,
		presetColorScheme: storeOptions.presetColorScheme ?? local.theme.defaultScheme,
	});
	const [snapshot, setSnapshot] = createSignal(store.getState());

	onMount(() => {
		retainSharedColorSchemeStore();
		const unsub = store.subscribe(() => setSnapshot(store.getState()));
		onCleanup(() => {
			unsub();
			releaseSharedColorSchemeStore();
		});
	});

	const colorScheme = () => snapshot().colorScheme;
	const resolvedColorScheme = () => snapshot().resolvedColorScheme;
	const colorSchemeList = createMemo(() => snapshot().colorSchemeList);
	const labelShort = createMemo(() => snapshot().labelShort);

	const colorSchemeValue = {
		colorScheme,
		resolvedColorScheme,
		colorSchemeList,
		labelShort,
		changeColorScheme: store.changeColorScheme,
	};

	const themeAccessor = () => local.theme.theme;

	return (
		<ColorSchemeContext.Provider value={colorSchemeValue}>
			<ThemeContext.Provider value={themeAccessor}>
				<DeviceSizeProvider breakpoints={local.breakpoints} breakpointsRem={local.breakpointsRem}>
					<ReducedMotionProvider reducedMotion={local.reducedMotion}>
						{local.children}
					</ReducedMotionProvider>
				</DeviceSizeProvider>
			</ThemeContext.Provider>
		</ColorSchemeContext.Provider>
	);
}

// packages/react/src/components/SingletonThemeProvider.tsx
import { useEffect, type ReactNode } from 'react';

import {
	peekOrCreateSharedColorSchemeStore,
	releaseSharedColorSchemeStore,
	retainSharedColorSchemeStore,
	type ColorSchemeStoreOptions,
	type CreatedTheme,
	type ReducedMotionPreference,
	type ThemeConfigInput,
} from '@ohJohny/theme-builder-core';

import { ThemeProviderTree } from './ThemeProviderTree';
import type { DeviceBreakpoints } from '../utils/types';

export type SingletonThemeProviderProps<C extends ThemeConfigInput> = Omit<
	ColorSchemeStoreOptions,
	'schemes'
> & {
	readonly theme: CreatedTheme<C>;
	readonly breakpoints?: Partial<DeviceBreakpoints>;
	/** @deprecated Use {@link SingletonThemeProviderProps.breakpoints} */
	readonly breakpointsRem?: Partial<DeviceBreakpoints>;
	/**
	 * `true` / `false` force reduced motion on or off; `'auto'` (default) follows
	 * OS `prefers-reduced-motion`. `false` is not recommended — prefer `'auto'`.
	 */
	readonly reducedMotion?: ReducedMotionPreference;
	readonly children: ReactNode;
};

export function SingletonThemeProvider<C extends ThemeConfigInput>(
	props: SingletonThemeProviderProps<C>,
) {
	const { children, breakpoints, breakpointsRem, reducedMotion, theme, ...storeOptions } = props;

	const store = peekOrCreateSharedColorSchemeStore({
		...storeOptions,
		schemes: theme.schemes,
		presetColorScheme: storeOptions.presetColorScheme ?? theme.defaultScheme,
	});

	useEffect(() => {
		retainSharedColorSchemeStore();
		return () => releaseSharedColorSchemeStore();
	}, []);

	return (
		<ThemeProviderTree
			store={store}
			theme={theme}
			breakpoints={breakpoints}
			breakpointsRem={breakpointsRem}
			reducedMotion={reducedMotion}
		>
			{children}
		</ThemeProviderTree>
	);
}
