// packages/react/src/components/ColorSchemeContext.tsx
import { createContext, useContext } from 'react';

import { createColorSchemeStore, type ColorSchemeId } from '@ohJohny/theme-builder-core';

import type { ColorSchemeStoreState, Theme } from '@ohJohny/theme-builder-core';

export type ColorSchemeContextValue = ReturnType<typeof createColorSchemeStore> & {
	readonly state: ColorSchemeStoreState;
};

export const ColorSchemeContext = createContext<ColorSchemeContextValue | null>(null);

export function useColorSchemeContext(): ColorSchemeContextValue {
	const context = useContext(ColorSchemeContext);
	if (!context) {
		throw new Error('useColorScheme must be used within a ThemeProvider');
	}
	return context;
}

export const ThemeContext = createContext<Theme | null>(null);

export function useTheme(): Theme {
	const theme = useContext(ThemeContext);
	if (!theme) {
		throw new ReferenceError('[useTheme] must be used within a ThemeProvider');
	}
	return theme;
}

export type { ColorSchemeId, ThemeMetaItem, ThemeStorageConfig } from '@ohJohny/theme-builder-core';

// packages/solid/src/components/ColorSchemeContext.ts
import type { Accessor } from 'solid-js';
import { createContext, useContext } from 'solid-js';

import type {
	ColorSchemeListItem,
	ColorSchemePreference,
	ThemeMetaItem,
} from '@ohJohny/theme-builder-core';

export type { ColorSchemeListItem };

export type ColorSchemeContextValue = {
	readonly colorScheme: Accessor<ColorSchemePreference>;
	readonly resolvedColorScheme: Accessor<string>;
	readonly colorSchemeList: Accessor<readonly ColorSchemeListItem[]>;
	readonly labelShort: Accessor<string>;
	readonly changeColorScheme: (next?: ColorSchemePreference) => void;
};

const ColorSchemeContext = createContext<ColorSchemeContextValue>();

export function useColorSchemeContext(): ColorSchemeContextValue {
	const context = useContext(ColorSchemeContext);
	if (!context) {
		throw new Error('useColorScheme must be used within a ThemeProvider');
	}
	return context;
}

export { ColorSchemeContext };

export type { ThemeMetaItem };
