// packages/react/src/components/ReducedMotionProvider.tsx
import { useMemo, useSyncExternalStore, type ReactNode } from 'react';
import {
	getReducedMotionSnapshot,
	resolveReducedMotion,
	subscribeReducedMotion,
	type ReducedMotionPreference,
} from '@ohJohny/theme-builder-core';

import { ReducedMotionContext } from './ReducedMotionContext';

export type ReducedMotionProviderProps = {
	/**
	 * `true` / `false` force reduced motion on or off; `'auto'` (default) follows
	 * OS `prefers-reduced-motion`. `false` is not recommended — prefer `'auto'`.
	 */
	readonly reducedMotion?: ReducedMotionPreference;
	readonly children: ReactNode;
};

/**
 * Subscribes to the shared `prefers-reduced-motion` pipeline and exposes
 * `reducedMotion` on context. Mounted by {@link ThemeProviderTree}.
 */
export function ReducedMotionProvider(props: ReducedMotionProviderProps) {
	const { reducedMotion: reducedMotionOverride, children } = props;

	const reducedMotionFromOs = useSyncExternalStore(
		subscribeReducedMotion,
		getReducedMotionSnapshot,
		getReducedMotionSnapshot,
	);

	const reducedMotion = resolveReducedMotion(reducedMotionOverride, reducedMotionFromOs);

	const value = useMemo(() => ({ reducedMotion }), [reducedMotion]);

	return (
		<ReducedMotionContext.Provider value={value}>{children}</ReducedMotionContext.Provider>
	);
}

// packages/solid/src/components/ReducedMotionProvider.tsx
/** @jsxImportSource solid-js */
import {
	createMemo,
	createSignal,
	onCleanup,
	splitProps,
	type Accessor,
	type JSX,
} from 'solid-js';
import {
	getReducedMotionSnapshot,
	resolveReducedMotion,
	subscribeReducedMotion,
	type ReducedMotionPreference,
} from '@ohJohny/theme-builder-core';

import { ReducedMotionContext } from './ReducedMotionContext';

export type ReducedMotionProviderProps = {
	/**
	 * `true` / `false` force reduced motion on or off; `'auto'` (default) follows
	 * OS `prefers-reduced-motion`. `false` is not recommended — prefer `'auto'`.
	 */
	readonly reducedMotion?: ReducedMotionPreference;
};

/**
 * Subscribes to the shared `prefers-reduced-motion` pipeline and exposes
 * `reducedMotion` on context. Mounted by {@link ThemeProvider}.
 */
export function ReducedMotionProvider(
	props: ReducedMotionProviderProps & { children?: JSX.Element },
) {
	const [local] = splitProps(props, ['children', 'reducedMotion']);

	const [reducedMotionFromOs, setReducedMotionFromOs] = createSignal(false);
	const unsub = subscribeReducedMotion(() => {
		setReducedMotionFromOs(getReducedMotionSnapshot());
	});
	setReducedMotionFromOs(getReducedMotionSnapshot());
	onCleanup(unsub);

	const reducedMotion: Accessor<boolean> = createMemo(() =>
		resolveReducedMotion(local.reducedMotion, reducedMotionFromOs()),
	);

	const value = { reducedMotion };

	return (
		<ReducedMotionContext.Provider value={value}>{local.children}</ReducedMotionContext.Provider>
	);
}
