// packages/react/src/components/useColorSchemeTogglePosition.ts
import { useEffect, type RefObject } from 'react';

import { updateColorSchemeTogglePosition } from '@ohJohny/theme-builder-core';

export function useColorSchemeTogglePosition(ref: RefObject<HTMLElement | null>): void {
	useEffect(() => {
		const el = ref.current;
		if (!el) return;

		const update = () => {
			if (ref.current) updateColorSchemeTogglePosition(ref.current);
		};

		update();

		if (typeof ResizeObserver === 'undefined') return;

		const observer = new ResizeObserver(update);
		observer.observe(el);
		return () => observer.disconnect();
	}, [ref]);
}

// packages/solid/src/useColorSchemeTogglePosition.ts
import type { Accessor } from 'solid-js';
import { createRenderEffect, onCleanup } from 'solid-js';

import { updateColorSchemeTogglePosition } from '@ohJohny/theme-builder-core';

export function useColorSchemeTogglePosition(buttonRef: Accessor<HTMLElement | undefined>): void {
	createRenderEffect(() => {
		const el = buttonRef();
		if (!el) return;

		updateColorSchemeTogglePosition(el);

		if (typeof ResizeObserver === 'undefined') return;

		const observer = new ResizeObserver(() => {
			const current = buttonRef();
			if (current) updateColorSchemeTogglePosition(current);
		});
		observer.observe(el);
		onCleanup(() => observer.disconnect());
	});
}
